name = "SDL3_Renderer"
type = "Module"
version = { major = 0, minor = 0, patch = 1 }
author = "armscream"
description = "SDL3 GPU renderer."
flags = ["Runtime"]
capabilities = ["Renderer", "GPU", "Materials", "Textures"]
