api_version = 1
name = "Miniaudio"
component_kind = "Module"
type = "Audio"
version = { major = 0, minor = 0, patch = 1 }
author = "armscream"
description = "Stub miniaudio module — full impl pending."
flags = ["Runtime"]
capabilities = ["Audio"]
dependency_count = 1

[[dependencies]]
name = "BF_DAG"
min_version = { major = 0, minor = 0, patch = 1 }
max_version = { major = 9, minor = 9, patch = 9 }
has_min_version = true
has_max_version = true
optional = false
