api_version = 1
name = "BF_ECS"
component_kind = "Module"
type = "ECS"
version = { major = 0, minor = 0, patch = 1 }
author = "armscream"
description = "ECS for Bifrost Engine."
flags = ["Runtime"]
capabilities = ["ECS"]
dependency_count = 1

[[dependencies]]
name = "BF_DAG"
min_version = { major = 0, minor = 0, patch = 1 }
max_version = { major = 9, minor = 9, patch = 9 }
has_min_version = true
has_max_version = true
optional = false
