api_version = 1
name = "BF_DAG"
component_kind = "Module"
type = "Scheduler"
version = { major = 0, minor = 0, patch = 1 }
author = "armscream"
description = "DAG Scheduler for Bifrost Engine."
flags = ["Runtime"]
capabilities = ["Custom"]
dependency_count = 0
