project_name = "New Project"

[version]
major = 0
minor = 0
patch = 1

[[modules]]
name = "Bifrost_Renderer"
enabled = true
[modules.version]
major = 0
minor = 0
patch = 1

[[modules]]
name = "BF_DAG"
enabled = true
[modules.version]
major = 0
minor = 0
patch = 1

[[modules]]
name = "BF_ECS"
enabled = true
[modules.version]
major = 0
minor = 0
patch = 1

[[modules]]
name = "BF_Input"
enabled = false
[modules.version]
major = 0
minor = 0
patch = 1

[[modules]]
name = "Miniaudio"
enabled = false
[modules.version]
major = 0
minor = 0
patch = 1

[[modules]]
name = "Box3D_Physics"
enabled = false
[modules.version]
major = 0
minor = 0
patch = 1

[[modules]]
name = "ATLAS-RMGUI"
enabled = false
[modules.version]
major = 0
minor = 0
patch = 1

[[modules]]
name = "BF_Scripting"
enabled = false
[modules.version]
major = 0
minor = 0
patch = 1

[[modules]]
name = "BF_Editor"
enabled = false
[modules.version]
major = 0
minor = 0
patch = 1

[[modules]]
name = "ENet"
enabled = false
[modules.version]
major = 0
minor = 0
patch = 1


[[extensions]]
name = "Example Extension"
enabled = false
[extensions.version]
major = 0
minor = 0
patch = 1


[[plugins]]
name = "Example Plugin"
enabled = false
[plugins.version]
major = 0
minor = 0
patch = 1

